-- Deprecated file kept for reference. Do not use self-referential subqueries on
-- public.user_roles policies because they can recurse under RLS.
-- Use public.has_role(auth.uid(), 'admin')-based policies instead.
